[programs.localnet]
# fws_verify = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
fws_raffle_program = "AUV6acTchdGPST1pexjEMTJ8KehrjQHJoXwiMntdYJ7p"

[programs.devnet]
# fws_verify = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
fws_raffle_program = "AUV6acTchdGPST1pexjEMTJ8KehrjQHJoXwiMntdYJ7p"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/khalilbrown/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
