version: 2.1
orbs: 
  discord: teka23/discord@0.0.1
# Define the jobs we want to run for this project
jobs:
  build-prod:
    docker:
      - image: node:latest
    environment:
          CI: false
          NODE_ENV: development
    steps:
      - checkout
      - run: apt-get update && apt-get -y install rsync
      - run: cp ./floorwatchers/.env.production ./floorwatchers/.env
      - run: cd ./floorwatchers/ && npm install
      - run: cd ./floorwatchers/ && npm run build
      - run: rsync -e "ssh -o StrictHostKeyChecking=no" -va ./packages/floorwatchers/build/ $USER@$IP:/var/www/floorwatchers.com/html/
      - discord/status:
          fail_only: false
          # mentions: 'Nafis#1303,solfist3r#4247'
          only_for_branches: 'dev,master'
  build-dev:
    docker:
      - image: node:latest
    environment:
          CI: false
          NODE_ENV: development
    steps:
      - checkout
      - run: apt-get update && apt-get -y install rsync
      - run: cp ./floorwatchers/.env.development ./floorwatchers/.env.production
      - run: cd ./floorwatchers/ && npm install
      - run: cd ./floorwatchers/ && npm run build
      - run: rsync -e "ssh -o StrictHostKeyChecking=no" -va ./floorwatchers/build/ $USER@$IP:/var/www/dev.floorwatchers.com/html/
      - discord/status:
          fail_only: false
          # mentions: 'Nafis#1303,solfist3r#4247'
          only_for_branches: 'dev,master'

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - build-prod:
          filters:
            branches:
              only:
                - master
      - build-dev:
          filters:
              branches:
                only:
                  - dev